Repository pknu-wap/2025_1_app2_FE, pull requests merged in 2025-05, with the labels that each got.

#21 [feat] 반경 nkm 내 팟 조회 및 참여/생성 모달 구현
  app2_client/assets/kakao_map.html
  app2_client/ios/Podfile.lock
  app2_client/ios/Runner.xcodeproj/project.pbxproj
  app2_client/ios/Runner/AppDelegate.swift
  app2_client/ios/Runner/Info.plist
  app2_client/lib/app.dart
  app2_client/lib/constants/api_constants.dart
  app2_client/lib/main.dart
  app2_client/lib/models/party_create_request.dart
  app2_client/lib/models/party_model.dart
  app2_client/lib/models/user_model.dart
  app2_client/lib/providers/auth_provider.dart
  app2_client/lib/screens/destination_map_screen.dart
  app2_client/lib/screens/destination_select_screen.dart
  app2_client/lib/screens/login_screen.dart
  app2_client/lib/screens/party_create_screen.dart
  app2_client/lib/screens/party_map_screen.dart
  app2_client/lib/screens/party_screen.dart
  app2_client/lib/screens/search_address_screen.dart
  app2_client/lib/screens/signup_screen.dart
  app2_client/lib/services/auth_service.dart
  app2_client/lib/services/party_service.dart
  app2_client/lib/widgets/google_login_button.dart
  app2_client/lib/widgets/party_create_modal.dart
  app2_client/lib/widgets/party_join_modal.dart
  app2_client/macos/Flutter/GeneratedPluginRegistrant.swift
  app2_client/pubspec.lock
  app2_client/pubspec.yaml
  app2_client/windows/flutter/generated_plugin_registrant.cc
  app2_client/windows/flutter/generated_plugins.cmake
Labels: 박준용, 진행중

#31 fix: 안드로이드에서 구글 로그인 오류 해결
  app2_client/android/app/build.gradle.kts
  app2_client/android/app/google-services.json
  app2_client/android/app/src/main/AndroidManifest.xml
  app2_client/android/settings.gradle.kts
  app2_client/firebase.json
  app2_client/ios/Podfile
  app2_client/ios/Podfile.lock
  app2_client/ios/Runner.xcodeproj/project.pbxproj
  app2_client/lib/firebase_options.dart
  app2_client/lib/main.dart
  app2_client/lib/screens/destination_map_screen.dart
  app2_client/macos/Flutter/GeneratedPluginRegistrant.swift
  app2_client/macos/Runner.xcodeproj/project.pbxproj
  app2_client/macos/Runner/GoogleService-Info.plist
  app2_client/pubspec.lock
  app2_client/pubspec.yaml
  app2_client/windows/flutter/generated_plugin_registrant.cc
  app2_client/windows/flutter/generated_plugins.cmake
Labels: bug

#35 [feat] 출발지 지도 선택 화면 추가 및 GPS 기반 초기 위치 설정
  app2_client/lib/screens/destination_select_screen.dart
  app2_client/lib/screens/start_map_screen.dart
  app2_client/lib/widgets/party_create_modal.dart
Labels: feat, 진행중

#37 [feat] 파티참여 및 경유지 추가 기능구현
  app2_client/lib/services/party_service.dart
  app2_client/lib/widgets/party_join_modal.dart
Labels: 진행중

#40 feat: 내 파티 정보 페이지 생성 및 파티 생성 후 자동 이동 연동
  app2_client/lib/models/party_detail_model.dart
  app2_client/lib/screens/my_party_screen.dart
  app2_client/lib/services/party_service.dart
  app2_client/lib/widgets/party_create_modal.dart
Labels: feat, 진행중

#41 [Feature] 성은의 변경사항
  app2_client/lib/screens/destination_select_screen.dart
  app2_client/lib/screens/login_screen.dart
  app2_client/lib/screens/my_page.dart
  app2_client/lib/screens/my_page_content.dart
  app2_client/lib/screens/my_page_popup.dart
  app2_client/lib/screens/signup_screen.dart
  app2_client/lib/services/profile_service.dart
  app2_client/macos/Flutter/GeneratedPluginRegistrant.swift
  app2_client/pubspec.lock
  app2_client/pubspec.yaml
Labels: 성은

#43 [Feature] 토큰 저장 및 리팩토링
  app2_client/lib/app.dart
  app2_client/lib/constants/api_constants.dart
  app2_client/lib/interceptor/token_interceptor.dart
  app2_client/lib/main.dart
  app2_client/lib/providers/auth_provider.dart
  app2_client/lib/screens/party_map_screen.dart
  app2_client/lib/screens/root_screen.dart
  app2_client/lib/services/auth_service.dart
  app2_client/lib/services/dio_client.dart
  app2_client/lib/services/party_service.dart
  app2_client/lib/services/secure_storage_service.dart
  app2_client/lib/widgets/party_create_modal.dart
  app2_client/lib/widgets/party_join_modal.dart
  app2_client/linux/flutter/generated_plugin_registrant.cc
  app2_client/linux/flutter/generated_plugins.cmake
  app2_client/macos/Flutter/GeneratedPluginRegistrant.swift
  app2_client/pubspec.lock
  app2_client/pubspec.yaml
  app2_client/windows/flutter/generated_plugin_registrant.cc
  app2_client/windows/flutter/generated_plugins.cmake
Labels: 완료

#45 [feature] sms 인증
  app2_client/ios/Podfile.lock
  app2_client/ios/Runner.xcodeproj/project.pbxproj
  app2_client/ios/Runner/Info.plist
  app2_client/lib/app.dart
  app2_client/lib/constants/api_constants.dart
  app2_client/lib/models/sms_session_model.dart
  app2_client/lib/models/sms_verify_model.dart
  app2_client/lib/providers/auth_provider.dart
  app2_client/lib/screens/login_screen.dart
  app2_client/lib/screens/root_screen.dart
  app2_client/lib/screens/signup_screen.dart
  app2_client/lib/screens/sms_certification_screen.dart
  app2_client/lib/services/auth_service.dart
  app2_client/linux/flutter/generated_plugin_registrant.cc
  app2_client/linux/flutter/generated_plugins.cmake
  app2_client/macos/Flutter/GeneratedPluginRegistrant.swift
  app2_client/pubspec.lock
  app2_client/pubspec.yaml
  app2_client/windows/flutter/generated_plugin_registrant.cc
  app2_client/windows/flutter/generated_plugins.cmake
Labels: feat

#56 [feat] 경유지 및 정산자 기능 추가
  app2_client/assets/kakao_map.html
  app2_client/assets/kakao_party_map.html
  app2_client/lib/models/join_request_model.dart
  app2_client/lib/models/location_model.dart
  app2_client/lib/models/party_detail_model.dart
  app2_client/lib/models/party_member_model.dart
  app2_client/lib/models/stopover_model.dart
  app2_client/lib/screens/my_party_screen.dart
  app2_client/lib/screens/stopover_setting_screen.dart
  app2_client/lib/services/party_service.dart
  app2_client/pubspec.yaml
Labels: 진행중
